"""Update table contacts

Revision ID: 076e24b5aafe
Revises: 06f5a411cbf1
Create Date: 2023-04-15 23:59:30.343168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076e24b5aafe'
down_revision = '06f5a411cbf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'start_study')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('start_study', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
